### ISSUE TITLE
Please add `Database logging` to endev

### ISSUE THREAD

**Issue by falco010** [Skullsneeze/Quick-Drush#2]
Of is dat geen goed idee?

**Comment by Skullsneeze** [comment]
Database logging kan best zwaar zijn, zeker op grotere websites, waarschijnlijk is dit dus niet de beste oplossing.

Je kan natuurlijk altijd het `endev` command als volgt gebruiken `endev; en dblog`

**Comment by falco010** [comment]
Bedankt Martijn.

Op 2 juni 2015 13:37 schreef Martijn <notifications@github.com>:

> Database logging kan best zwaar zijn, zeker op grotere websites,
> waarschijnlijk is dit dus niet de beste oplossing.
>
> Je kan natuurlijk altijd het endev command als volgt gebruiken endev; en
> dblog
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Skullsneeze/Quick-Drush/issues/2#issuecomment-107924253>
> .
>



-- 

Met vriendelijke groet,

Falco Bahnerth
Developer

CODE Internet Applications
Frederik Matthesstraat 30
2613ZZ Delft

falco@code.nl

T: +31 (0) 15 213 06 00
F: +31 (0) 15 213 04 59

http://www.code.nl
